### ISSUE TITLE
麦克风用不了

### ISSUE THREAD

**Issue by Dinner219038** [ChgygLin/thinkbook16p-2021-5800H-EFI#1]

**Comment by Dinner219038** [comment]
[AMDMicrophone](https://github.com/qhuyduong/AMDMicrophone)](https://github.com/qhuyduong/AMDMicrophone)

**Comment by ChgygLin** [comment]
这个问题暂时无解。
https://dortania.github.io/OpenCore-Post-Install/universal/audio.html#no-mic-on-amd

**Comment by ChgygLin** [comment]
@Dinner219038 
Hi, 目前版本已支持mic～
