### ISSUE TITLE
加入RadeonSensor

### ISSUE THREAD

**Issue by Dinner219038** [ChgygLin/thinkbook16p-2021-5800H-EFI#2]
[RadeonSensor](https://github.com/NootInc/RadeonSensor) 支持AMD iGPU

**Comment by ChgygLin** [comment]
测试过了RadeonSensor，不打算支持。
1. iGPU温度不支持istat，只能使用RadeonGadget显示。
2. 目前istat支持CPU温度显示，iGPU温度和CPU温度差别不大。
